on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  TZ: 'UTC'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Known JSON
        uses: actions/cache@v3
        with:
          key: known
          path: known.json
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Scrape
        run: node index